version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbit
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Web UI: http://localhost:15672 (guest/guest)


volumes:
  pgdata: